MIN_ELO = 2000
MAX_GAMES = 5000
MODEL_SUB_NAME = f"{MIN_ELO}_{MAX_GAMES}"

DATA_FOLDER_PATH = "data/"

DATA_PATH = f"{DATA_FOLDER_PATH}raw/lichess_db_standard_rated_2017-02.pgn"
DATA_WRITE_PATH = f"{DATA_FOLDER_PATH}lichess_db_winElo_{MIN_ELO}_amount_{MAX_GAMES}.pgn"

MODELS_FOLDER_PATH = "models/"

BATCH_SIZE = 32
CONTEXT_SIZE = 10
INPUT_SIZE = CONTEXT_SIZE - 1
N_EMBED = 256
N_HEADS = 8
N_LAYERS = 6
DROPOUT = 0.0
LR = 3e-4

SEED = 1234321
