MIN_ELO = 2000
MAX_GAMES = 100000
MODEL_SUB_NAME = f"{MIN_ELO}_{MAX_GAMES}"

DATA_FOLDER_PATH = "data/"

DATA_PATH = f"{DATA_FOLDER_PATH}raw/lichess_db_standard_rated_2017-02.pgn"
DATA_WRITE_PATH = f"{DATA_FOLDER_PATH}lichess_db_filtered_{MODEL_SUB_NAME}.pgn"

MODELS_FOLDER_PATH = "models/"
MODEL_FILE_PATH = f"{MODELS_FOLDER_PATH}model_{MODEL_SUB_NAME}.pt"
METADATA_FILE_PATH = f"{MODELS_FOLDER_PATH}metadata_{MODEL_SUB_NAME}.json"

EPOCHS = 3
BATCH_SIZE = 256
CONTEXT_SIZE = 16
INPUT_SIZE = CONTEXT_SIZE - 1
N_EMBED = 256
N_HEADS = 8
N_LOOPS = 4
DROPOUT = 0.1
LR = 3e-4
WEIGHT_DECAY = 0.1
WARMUP_FRAC = 0.03
MIN_LR_RATIO = 0.1
GRAD_CLIP = 1.0

SEED = 1234321

SPLIT_NAMES = ("train", "val", "test")
SPLIT_RATIOS = (0.8, 0.1, 0.1)
BATCHES_FOLDER_PATH = (
    f"{DATA_FOLDER_PATH}batches/{MODEL_SUB_NAME}_ctx{CONTEXT_SIZE}_bs{BATCH_SIZE}/"
)
